update ActorPage
ServerIbraimovUa/movies_project pull request #58
Opened 2024-01-13 17:30 UTC by Oksana-Tnt

2024-01-13 17:39 UTC, ServerIbraimovUa requested changes
конфликты

2024-01-13 18:07 UTC, Oksana-Tnt reviewed
done

2024-01-14 18:07 UTC, nightven approved these changes

2024-01-14 18:12 UTC, nightven commented
конфлікти так і залишились

2024-01-17 16:59 UTC, ServerIbraimovUa approved these changes

2024-01-17 16:59 UTC, merged